Add validation check to block duplicate title_abbrev in the same language:version.
awsdocs/aws-doc-sdk-examples-tools pull request #49
Opened 2024-07-11 19:32 UTC by DavidSouther

This applies during late validation, so merging tributaries can cause it, even if it doesn't happen in each tributary.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-12 21:08 UTC, Laren-AWS requested changes
This appears to be a bit more nuanced than just title_abbrev on its own. What's actually prohibited is to have different examples (i.e. with different example IDs) that have a duplicate combination of `category` + `title_abbrev`.

See [Bedrock Runtime](https://docs.aws.amazon.com/code-library/latest/ug/bedrock-runtime_code_examples.html) for an example.

You can also see the false positives by running this code against the current metadata in aws-docs-sdk-examples repo.

2024-07-12 21:32 UTC, DavidSouther commented
Done. Test in https://github.com/awsdocs/aws-doc-sdk-examples/pull/6659

2024-07-12 22:43 UTC, Laren-AWS requested changes

2024-07-12 22:43 UTC, Laren-AWS commented on aws_doc_sdk_examples_tools/metadata.py
> +        if category is None or category == "":
Merge error? You're putting this back to the old pattern.

2024-07-12 22:43 UTC, Laren-AWS commented on aws_doc_sdk_examples_tools/metadata.py
> +    validation = ValidationConfig() if validation is None else validation
Merge error?

2024-07-12 22:43 UTC, Laren-AWS commented on aws_doc_sdk_examples_tools/metadata_errors.py
> +        return f"multiple API examples found with conflicting title_abbrev: {self.title_abbrev} in {self.language}"
These are not API examples, they're other kinds of examples, so I'd just say "multiple examples found..."

Also, when I trigger this error by making broken metadata, the error is:

>In None at s3_Scenario_TrackUploadDownload, s3_Scenario_AbortMultipartUpload, multiple API examples found with conflicting title_abbrev: Delete incomplete multipart uploads in s3:Scenarios

"None" should be the filename, right?

2024-07-15 20:30 UTC, Laren-AWS approved these changes

2024-07-15 20:37 UTC, merged